import streamlit as st
from pathlib import Path
import json
st.set_page_config(layout="wide")
st.title("📊 Scraping")

file_path = Path("data/raw/trustpilot_reviews_production.json")

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

#st.write(data)

import pandas as pd

df = pd.DataFrame(data)
st.subheader("Raw data after basic cleaning")
st.markdown("""
- This section provides a first overview of the dataset that we scraped after basic cleaning. 
- The data was scraped from the Trustpilot platform.
- To this end, an automated web scraping pipeline was developed.
- Due to dynamically loaded content, a browser-based approach using Selenium was implemented to ensure reliable extraction of all relevant elements,
 including hidden or asynchronously loaded data.

""")
st.dataframe(df.head(20))

st.subheader("Data collection and rights")
st.markdown("""
- Customer reviews were collected from Trustpilot platform
- Publicly accessible,but not freely available for unrestricted reuse
- Reviews are generated by users of the platform, but the Trustpilot company owns and controls the distribution and use of this data
- Any reuse must comply with their legal and ethical guidelines.
- Collecting only publicly accessible data
- Avoiding personal or sensitive information
- Using the data exclusively for non-commercial, educational purposes
""")

st.subheader("Technical Problems and challenges with Scraping")

df = pd.DataFrame({
    "Problem with scraping": [
        "Dynamical content",
        "Detection bots",
        "Different scraping iterations",
        "Duplicates,overlapping contents",
        "Data incompleteness"
    ],
    "Solution": [
        "Adapt scraping script each time",
        "Imitate human behaviour with timeouts",
        "Standardize the data",
        "Search and delete them in cleaning process",
        "Unavoidable, not solvable"
    ]
})

st.table(df)

